[SPIKE] Index virtual objects as both items and virtual objects
sul-dlss/dor_indexing_app pull request #748
Opened 2022-02-14 22:06 UTC by mjgiarlo

## Why was this change made?

This would make it easier for Argo users to find and operate in bulk on virtual objects. Whether it is valuable, or has other risks or side effects, would be worth discussing. I could also be convinced that we could/should use the existing has_constituents_ssim field for this somehow?

## How was this change tested?

CI

## Which documentation and/or configurations were updated?

None

2022-02-14 22:52 UTC, justinlittman approved these changes
Approve pending consideration of comment and would like @jcoyne to weigh in whether this might have other effects.

2022-02-14 22:52 UTC, justinlittman commented on app/indexers/identity_metadata_indexer.rb
> +      return ['item'] unless cocina_object.structural&.hasMemberOrders&.first&.members
`.present?` to avoid `[]`?

2022-02-14 22:57 UTC, jcoyne commented
Is there a reason we can't use the existing has_constituents_ssim for this?

2022-02-14 22:59 UTC, jcoyne requested changes

2022-02-14 22:59 UTC, jcoyne commented on app/indexers/identity_metadata_indexer.rb
> +      'objectType_ssim' => object_types,
This field is used by Argo to determine what partials to display and I'd be a bit hesitant to add values to it that are not expected.

2022-02-14 23:09 UTC, mjgiarlo commented
@jcoyne 💬 
> Is there a reason we can't use the existing has_constituents_ssim for this?

That is a question I had as well up in the PR description. I can look into it.

2022-02-15 00:30 UTC, mjgiarlo commented
Superseded by https://github.com/sul-dlss/argo/pull/3110, closing

2022-02-15 00:30 UTC, closed without merging