use cocina-models factory for test objects
sul-dlss/dor_indexing_app pull request #834
Opened 2022-04-30 04:41 UTC by ndushay

## Why was this change made? 🤔

to reduce boilerplate in our specs.

Closes #831

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test) that exercise indexing*** (e.g. searches in Argo for newly created/updated items, access_indexing_spec) and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-04-30 05:13 UTC, ndushay reviewed
Having everything named "test object" isn't so clever, and not distinguishing between label and title values in our factories, etc.   I just filed sul-dlss/cocina-models/issues/454 about this.  

I was very aware of the obfuscation of some indexing by using the same values in different factory objects when doing this PR.

2022-05-02 11:20 UTC, justinlittman requested changes
Looks good. Minor comment and a question.

2022-05-02 11:20 UTC, justinlittman commented on spec/indexers/collection_title_indexer_spec.rb
> +        build(:collection, id: collection_druid).new(
Can you just pass `title: 'Collection test object'` to `build` instead of using `.new(description: ...)`?

2022-05-02 11:20 UTC, justinlittman commented on spec/indexers/composite_indexer_spec.rb
> +        'metadata_source_ssi' => 'DOR',
Why did this change?

2022-05-02 11:20 UTC, justinlittman commented on spec/indexers/content_metadata_indexer_spec.rb
> +        {
Thank you.

2022-05-02 18:07 UTC, justinlittman approved these changes

2022-05-02 18:07 UTC, merged