desc_metadata_indexer: avoid error when genre value is nil
sul-dlss/dor_indexing_app pull request #886
Opened 2022-08-08 21:17 UTC by ndushay

## Why was this change made? 🤔

To address https://app.honeybadger.io/projects/49898/faults/87288421

## How was this change tested? 🤨

⚡ ⚠ If this change has cross service impact, ***run [integration tests](https://github.com/sul-dlss/infrastructure-integration-test) that exercise indexing*** (e.g. searches in Argo for newly created/updated items, access_indexing_spec) and/or test in [stage|qa] environment, in addition to specs. ⚡

2022-08-08 21:19 UTC, ndushay commented
tagging @arcadiafalcone to make sure she's okay wth this.  Seems like a new error probably for one set of objects ...

2022-08-08 21:20 UTC, jcoyne requested changes
Can you please add a test that demonstrates how this change fixes the problem?

2022-08-08 22:24 UTC, arcadiafalcone commented
@ndushay This error is possible when creating cocina without routing through MODS first. This also relates to the conversation about requiring certain properties in validation to catch orphan attributes without a corresponding value or value-equivalent property, which would be a more comprehensive way of addressing the issue.

Slack thread from when this was done for subject: https://stanfordlib.slack.com/archives/C09M7P91R/p1659439518438329

2022-08-10 20:50 UTC, ndushay commented
@jcoyne test added.

@arcadiafalcone I'll assume you'll make a ticket or whatever to address this problem with validation.

2022-08-10 20:53 UTC, ndushay commented
@arcadiafalcone also assume you or someone will reindex all the affected items?  (fewer than 30, I think, per honeybadger alert.)

2022-08-11 16:18 UTC, arcadiafalcone commented
Ticket for the general issue is here: https://github.com/sul-dlss/cocina-models/issues/510

2022-08-11 22:25 UTC, arcadiafalcone commented
I've added required property lists to https://github.com/sul-dlss/cocina-models/issues/510.

2022-08-12 16:10 UTC, jcoyne approved these changes

2022-08-12 18:54 UTC, merged